version: '3.7'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    volumes:
      - db-vol:/var/lib/mysql
      - ${PWD}/config/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=YES
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - LANGUAGE=en_US.UTF-8
    restart: always
    container_name: mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  haproxy:
    image: haproxy:1.9
    volumes:
      - ${PWD}/config/haproxy-base.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ${PWD}/config/myselfsigned.pem:/etc/ssl/myselfsigned.pem
    ports:
      - 80:80
      - 443:443
    container_name: haproxy
volumes:
  db-vol: