version: '3.7'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - db-vol:/var/lib/mysql
      - ${PWD}/config/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - LANGUAGE=en_US.UTF-8
    container_name: mysql
    restart: always
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
volumes:
  db-vol: